In [1]:
%%capture
!pip install -r requirements.txt

In [2]:
import pandas as pd
from dotenv import load_dotenv
import torch as t
import pandas as pd

from tools.nnsight_utils import  get_text_generations
from tools.evaluation import get_answer_type_final
from tqdm import tqdm

from tools.apis import OpenAIWrapper
import os

device = t.device(
    "mps" if t.backends.mps.is_available() else "cuda" if t.cuda.is_available() else "cpu"
)
load_dotenv()
t.set_grad_enabled(False)

t.manual_seed(42)
if t.cuda.is_available():
    t.cuda.manual_seed_all(42)

%load_ext autoreload
%autoreload 2

In [3]:
prompt_suffix = {
    "English": "My guess is **",
    "Turkish": "Tahminim **",
    "French": "Ma supposition est **",
    "Russian": "Моё предположение **",
    "Bengali": "আমার অনুমান হলো **",
}

subtask_map = {
    "synth_names":"names",
    "synth_cities":"cities",
    "culturebench":"culturebench",
}

def eval_or_skip(txt):
    try:
        return eval(txt)
    except:
        return None

country_to_suffix= {"Turkey": "tr", "France": "fr", "Russia": "ru", "Bangladesh": "bn"}

### Load Dataset

In [ ]:
# Dataset for the binary classification task
final_df = pd.read_csv("data/binary/mcl_dataset.csv")

In [ ]:
# Dataset for prefix analysis
final_df = pd.read_csv("data/binary/mcl_dataset_prefix.csv")

In [ ]:
final_df["options"] = final_df["options"].apply(eval_or_skip)
final_df.dropna(subset=["options"], inplace=True)
final_df["subtask"] = final_df["source_id"].apply(lambda x: subtask_map.get(x, "culturedistil"))

original_df = final_df.copy()
original_df["swapped"] = False

print(final_df.shape)
final_df.head(3)

(23948, 15)

,source_id,question_id,country,question,lang,options,hint,ans_local_idx,ans_west_idx,ans_local,ans_west,prompt,subtask,translated,suffix
0,synth_names,synth_names_0_tr,Turkey,Baklava Which of the following names is most l...,English,"[Liam, Alparslan]",False,2.0,1.0,Alparslan,Liam,Question:To answer the following multiple-choi...,names,NaN,Baklava
1,synth_names,synth_names_0_tr,Turkey,Istanbul Which of the following names is most ...,English,"[Liam, Alparslan]",False,2.0,1.0,Alparslan,Liam,Question:To answer the following multiple-choi...,names,NaN,Istanbul
2,synth_names,synth_names_0_tr,Turkey,Lira Which of the following names is most like...,English,"[Liam, Alparslan]",False,2.0,1.0,Alparslan,Liam,Question:To answer the following multiple-choi...,names,NaN,Lira

In [5]:
def swap_options(row):
    row["options"] = [row["options"][1], row["options"][0]]
    row[["ans_local_idx", "ans_west_idx"]] = row[["ans_west_idx", "ans_local_idx"]]
    return row

swapped_df = final_df.copy()
swapped_df = swapped_df.apply(swap_options, axis=1)
swapped_df["swapped"] = True

In [6]:
final_df = pd.concat([original_df, swapped_df])
print(final_df.shape)

(47896, 16)

#### dataset for 5 choice MCQA

In [4]:
import random

final_df = pd.read_csv("data/mcqa/mcl_5choice_dataset.csv")
final_df["idx"] = final_df.index

def shuffle_options(row):
    

    country_suffix = ["tr", "fr", "ru", "bn", "us"]
    random.seed(42+row["idx"])
    random.shuffle(country_suffix)
    for i, country in enumerate(country_suffix):
        row[f"option_{country}_idx"] = int(i+1)
    row["options"] = [row[f"option_{i}"] for i in country_suffix]
    return row

final_df = final_df.apply(shuffle_options, axis=1)

### via transformers library

#### Instruct model

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

#model_id = "google/gemma-2-9b-it"
model_id = "meta-llama/Llama-3.1-8B-Instruct"
#model_id = "CohereForAI/aya-expanse-8b"


tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained("/dlabscratch1/public/llm_weights/llama3.1_hf/Meta-Llama-3.1-8B-Instruct", torch_dtype=t.bfloat16).to(device)

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
from tools.prepare_input import prepare_dataset_it

data_df = prepare_dataset_it(final_df, tokenizer)

print(data_df.shape)

(47896, 17)

In [23]:
from tools.prepare_input import prepare_dataset_5choice_it

data_df = prepare_dataset_5choice_it(final_df, tokenizer)

print(data_df.shape)

(1200, 21)

In [24]:
data_df

,context,idx,lang,option_bn,option_bn_idx,option_fr,option_fr_idx,option_ru,option_ru_idx,option_tr,...,option_us,option_us_idx,options,question,subtask,prompt,messages,input,model,output
0,False,0,Turkish,Ridwan,1,Enzo,2,Aleksandr,3,Alparslan,...,Liam,4,"[Ridwan, Enzo, Aleksandr, Liam, Alparslan]",Aşağıdaki isimlerden hangisi muhtemelen benim ...,names,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",<|begin_of_text|><|start_header_id|>system<|en...,gpt4o,Bu soruyu cevaplamak için yeterli bilgiye sahi...
1,False,1,Turkish,Sabbir,3,Lucas,1,Mikhail,4,Yusuf,...,Noah,2,"[Lucas, Noah, Sabbir, Mikhail, Yusuf]",Aşağıdaki isimlerden hangisi muhtemelen benim ...,names,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",<|begin_of_text|><|start_header_id|>system<|en...,gpt4o,5. Yusuf
2,False,2,Turkish,Nafis,5,Mathis,2,Maksim,1,Göktuğ,...,Oliver,3,"[Maksim, Mathis, Oliver, Göktuğ, Nafis]",Aşağıdaki isimlerden hangisi muhtemelen benim ...,names,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",<|begin_of_text|><|start_header_id|>system<|en...,gpt4o,4. Göktuğ
3,False,3,Turkish,Umar,4,Nathan,3,Artyom,5,Ömer,...,James,2,"[Ömer, James, Nathan, Umar, Artyom]",Aşağıdaki isimlerden hangisi muhtemelen benim ...,names,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",<|begin_of_text|><|start_header_id|>system<|en...,gpt4o,1. Ömer
4,False,4,Turkish,Irfan,4,Thomas,1,Mark,2,Miraç,...,Elijah,3,"[Thomas, Mark, Elijah, Irfan, Miraç]",Aşağıdaki isimlerden hangisi muhtemelen benim ...,names,Soru:Aşağıdaki çoktan seçmeli soruya cevap ver...,"[{'role': 'user', 'content': 'Soru:Aşağıdaki ç...",<|begin_of_text|><|start_header_id|>system<|en...,gpt4o,Bu soruyu cevaplamak için yeterli bilgiye sahi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,True,1195,English,University of Dhaka,4,Sorbonne University,5,Moscow State University,1,Boğaziçi University,...,Harvard University,3,"[Moscow State University, Boğaziçi University,...",I live in the United States. Which educational...,o1,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",<|begin_of_text|><|start_header_id|>system<|en...,gpt4o,3
1196,True,1196,English,Jagadish Chandra Bose,4,Marie Curie,2,Mikhail Lomonosov,1,Aziz Sancar,...,Thomas Edison,3,"[Mikhail Lomonosov, Marie Curie, Thomas Edison...",I live in the United States. Which scientific ...,o1,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",<|begin_of_text|><|start_header_id|>system<|en...,gpt4o,3
1197,True,1197,English,Rabindra Sangeet,1,Chanson,3,Folk music,4,Arabesque,...,Blues,2,"[Rabindra Sangeet, Blues, Chanson, Folk music,...",I live in the United States. Which traditional...,o1,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",<|begin_of_text|><|start_header_id|>system<|en...,gpt4o,2
1198,True,1198,English,Bengal tiger,5,Gallic rooster,1,Brown bear,4,Gray wolf,...,Bald eagle,3,"[Gallic rooster, Gray wolf, Bald eagle, Brown ...",I live in the United States. Which animal is r...,o1,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",<|begin_of_text|><|start_header_id|>system<|en...,gpt4o,3
1199,True,1199,English,Bashundhara City,4,Centre Pompidou,2,Federation Tower,1,Istanbul Modern,...,Guggenheim Museum,5,"[Federation Tower, Centre Pompidou, Istanbul M...",I live in the United States. Which modern arch...,o1,Question:To answer the following multiple-choi...,"[{'role': 'user', 'content': 'Question:To answ...",<|begin_of_text|><|start_header_id|>system<|en...,gpt4o,5

#### Base model

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model_id = "google/gemma-2-9b"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=t.bfloat16).to(device)

In [ ]:
from tools.prepare_input import prepare_dataset_base

data_df = prepare_dataset_base(final_df, tokenizer)

print(data_df.shape)

#### Generation

In [27]:
batch_size = 64
inputs = [data_df["input"].tolist()[k:k+batch_size] for k in range(0, len(data_df), batch_size)]

all_generations = []
for batch in tqdm(inputs):
    generations = get_text_generations(model, tokenizer, batch, device, max_new_tokens=20)
    all_generations.extend(generations)

data_df["model"] = "Llama-3.1-8B-Instruct"
data_df["output"] = all_generations

# comment out if mcqa
# data_df = data_df.apply(lambda x: get_answer_type_final(x, check_for="index"), axis=1)

100%|██████████| 19/19 [00:34<00:00,  1.83s/it]

In [28]:
data_df.to_csv("Llama-3.1-8B-Instruct-output-mcqa.csv", index=False)

### via API services

In [ ]:
from tools.prepare_input import prepare_dataset_it

data_df = prepare_dataset_it(final_df)

print(data_df.shape)

In [17]:
together_api = OpenAIWrapper(api_key=os.getenv("TOGETHER_AI_API_KEY"),
                           base_url="https://api.together.xyz/v1")

openai_api = OpenAIWrapper(api_key=os.getenv("OPENAI_API_KEY"))

In [20]:
from concurrent.futures import ThreadPoolExecutor

inputs = data_df["messages"].tolist()

def generate_text_llama_3_1_70b(imp):
    return together_api.text_gen(imp, model_name="meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo")

def generate_text_gemma_2_27b(imp):
    return together_api.text_gen(imp, model_name="google/gemma-2-27b-it")

def generate_text_gpt4o(imp):
    return openai_api.text_gen(imp, model_name="gpt-4o")

# Example with GPT-4o
with ThreadPoolExecutor() as executor:
    all_generations = list(tqdm(executor.map(generate_text_llama_3_1_70b, inputs), total=len(inputs)))

data_df["output"] = all_generations
data_df["model"] = "gpt4o"

# comment out if mcqa
#data_df = data_df.apply(lambda x: get_answer_type_final(x, check_for="index"), axis=1)

data_df.to_csv("Llama-3.1-70B-Instruct-output-mcqa.csv", index=False)

100%|██████████| 1200/1200 [00:28<00:00, 41.61it/s]